# Generated by Django 2.1.3 on 2018-11-08 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('price', models.IntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('listing_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artists.Artist')),
            ],
        ),
    ]
