# Generated by Django 2.1.3 on 2018-11-08 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True)),
                ('artist_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('member_since', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
